# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

import map
from matplotlib import pyplot as plt
import matplotlib.backends.backend_agg as agg
import simulation
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1113, 924)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_time = QtWidgets.QLabel(self.centralwidget)
        self.label_time.setGeometry(QtCore.QRect(30, 30, 151, 31))
        self.label_time.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_time.setFont(font)
        self.label_time.setTextFormat(QtCore.Qt.AutoText)
        self.label_time.setObjectName("label_time")
        self.label_vehicles = QtWidgets.QLabel(self.centralwidget)
        self.label_vehicles.setGeometry(QtCore.QRect(30, 100, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_vehicles.setFont(font)
        self.label_vehicles.setObjectName("label_vehicles")
        self.label_priority = QtWidgets.QLabel(self.centralwidget)
        self.label_priority.setGeometry(QtCore.QRect(30, 180, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_priority.setFont(font)
        self.label_priority.setObjectName("label_priority")
        self.label_stations = QtWidgets.QLabel(self.centralwidget)
        self.label_stations.setGeometry(QtCore.QRect(30, 140, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_stations.setFont(font)
        self.label_stations.setObjectName("label_stations")
        self.label_outages = QtWidgets.QLabel(self.centralwidget)
        self.label_outages.setGeometry(QtCore.QRect(30, 220, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_outages.setFont(font)
        self.label_outages.setObjectName("label_outages")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(580, 20, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_start.setFont(font)
        self.btn_start.setObjectName("btn_start")
        self.disp_time = QtWidgets.QLabel(self.centralwidget)
        self.disp_time.setGeometry(QtCore.QRect(240, 30, 111, 31))
        self.disp_time.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.disp_time.setFont(font)
        self.disp_time.setTextFormat(QtCore.Qt.AutoText)
        self.disp_time.setObjectName("disp_time")
        self.disp_vehicles = QtWidgets.QLabel(self.centralwidget)
        self.disp_vehicles.setGeometry(QtCore.QRect(240, 100, 111, 31))
        self.disp_vehicles.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.disp_vehicles.setFont(font)
        self.disp_vehicles.setTextFormat(QtCore.Qt.AutoText)
        self.disp_vehicles.setObjectName("disp_vehicles")
        self.disp_stations = QtWidgets.QLabel(self.centralwidget)
        self.disp_stations.setGeometry(QtCore.QRect(240, 140, 111, 31))
        self.disp_stations.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.disp_stations.setFont(font)
        self.disp_stations.setTextFormat(QtCore.Qt.AutoText)
        self.disp_stations.setObjectName("disp_stations")
        self.disp_priority = QtWidgets.QLabel(self.centralwidget)
        self.disp_priority.setGeometry(QtCore.QRect(240, 180, 111, 31))
        self.disp_priority.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.disp_priority.setFont(font)
        self.disp_priority.setTextFormat(QtCore.Qt.AutoText)
        self.disp_priority.setObjectName("disp_priority")
        self.disp_outages = QtWidgets.QLabel(self.centralwidget)
        self.disp_outages.setGeometry(QtCore.QRect(240, 220, 131, 31))
        self.disp_outages.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.disp_outages.setFont(font)
        self.disp_outages.setTextFormat(QtCore.Qt.AutoText)
        self.disp_outages.setObjectName("disp_outages")
        self.btn_step = QtWidgets.QPushButton(self.centralwidget)
        self.btn_step.setGeometry(QtCore.QRect(720, 20, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_step.setFont(font)
        self.btn_step.setObjectName("btn_step")
        self.btn_stop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stop.setGeometry(QtCore.QRect(860, 20, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_stop.setFont(font)
        self.btn_stop.setObjectName("btn_stop")
        self.label_map = QtWidgets.QLabel(self.centralwidget)
        self.label_map.setGeometry(QtCore.QRect(470, 70, 701, 631))
        self.label_map.setText("")
        self.label_map.setObjectName("label_map")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(420, 10, 20, 851))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_redistribution = QtWidgets.QLabel(self.centralwidget)
        self.label_redistribution.setGeometry(QtCore.QRect(30, 260, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_redistribution.setFont(font)
        self.label_redistribution.setObjectName("label_redistribution")
        self.disp_redistribution = QtWidgets.QLabel(self.centralwidget)
        self.disp_redistribution.setGeometry(QtCore.QRect(240, 260, 111, 31))
        self.disp_redistribution.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.disp_redistribution.setFont(font)
        self.disp_redistribution.setTextFormat(QtCore.Qt.AutoText)
        self.disp_redistribution.setObjectName("disp_redistribution")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(690, 740, 41, 31))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("gui_stuff/icons/eb2.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(750, 740, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(470, 700, 41, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("gui_stuff/icons/car_normal.png"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(530, 700, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(470, 740, 41, 31))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("gui_stuff/icons/car_priority.png"))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(530, 740, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(980, 700, 151, 31))
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(470, 780, 41, 31))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("gui_stuff/icons/ch_charged.png"))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(530, 780, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(470, 820, 41, 31))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("gui_stuff/icons/ch.png"))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(530, 820, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(920, 700, 41, 31))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("gui_stuff/icons/got_energy.png"))
        self.label_12.setObjectName("label_12")
        self.label_po_energy = QtWidgets.QLabel(self.centralwidget)
        self.label_po_energy.setGeometry(QtCore.QRect(30, 300, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_po_energy.setFont(font)
        self.label_po_energy.setObjectName("label_po_energy")
        self.label_car_wo_energy = QtWidgets.QLabel(self.centralwidget)
        self.label_car_wo_energy.setGeometry(QtCore.QRect(30, 340, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_car_wo_energy.setFont(font)
        self.label_car_wo_energy.setObjectName("label_car_wo_energy")
        self.label_car_charging = QtWidgets.QLabel(self.centralwidget)
        self.label_car_charging.setGeometry(QtCore.QRect(30, 380, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_car_charging.setFont(font)
        self.label_car_charging.setObjectName("label_car_charging")
        self.label_worst_time = QtWidgets.QLabel(self.centralwidget)
        self.label_worst_time.setGeometry(QtCore.QRect(30, 420, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_worst_time.setFont(font)
        self.label_worst_time.setObjectName("label_worst_time")
        self.label_architecture = QtWidgets.QLabel(self.centralwidget)
        self.label_architecture.setGeometry(QtCore.QRect(30, 460, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_architecture.setFont(font)
        self.label_architecture.setObjectName("label_architecture")
        self.disp_car_charging = QtWidgets.QLabel(self.centralwidget)
        self.disp_car_charging.setGeometry(QtCore.QRect(240, 380, 111, 31))
        self.disp_car_charging.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.disp_car_charging.setFont(font)
        self.disp_car_charging.setTextFormat(QtCore.Qt.AutoText)
        self.disp_car_charging.setObjectName("disp_car_charging")
        self.disp_po_energy = QtWidgets.QLabel(self.centralwidget)
        self.disp_po_energy.setGeometry(QtCore.QRect(240, 300, 111, 31))
        self.disp_po_energy.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.disp_po_energy.setFont(font)
        self.disp_po_energy.setTextFormat(QtCore.Qt.AutoText)
        self.disp_po_energy.setObjectName("disp_po_energy")
        self.disp_car_wo_energy = QtWidgets.QLabel(self.centralwidget)
        self.disp_car_wo_energy.setGeometry(QtCore.QRect(240, 340, 111, 31))
        self.disp_car_wo_energy.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.disp_car_wo_energy.setFont(font)
        self.disp_car_wo_energy.setTextFormat(QtCore.Qt.AutoText)
        self.disp_car_wo_energy.setObjectName("disp_car_wo_energy")
        self.disp_worst_time = QtWidgets.QLabel(self.centralwidget)
        self.disp_worst_time.setGeometry(QtCore.QRect(240, 420, 111, 31))
        self.disp_worst_time.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.disp_worst_time.setFont(font)
        self.disp_worst_time.setTextFormat(QtCore.Qt.AutoText)
        self.disp_worst_time.setObjectName("disp_worst_time")
        self.disp_architecture = QtWidgets.QLabel(self.centralwidget)
        self.disp_architecture.setGeometry(QtCore.QRect(240, 460, 111, 31))
        self.disp_architecture.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.disp_architecture.setFont(font)
        self.disp_architecture.setTextFormat(QtCore.Qt.AutoText)
        self.disp_architecture.setObjectName("disp_architecture")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(690, 820, 41, 31))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("gui_stuff/icons/eb2.png"))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(750, 820, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(690, 780, 41, 31))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("gui_stuff/icons/eb_outage.png"))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(750, 780, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(690, 700, 41, 31))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("gui_stuff/icons/po.png"))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(750, 700, 151, 31))
        self.label_14.setObjectName("label_14")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(920, 740, 41, 31))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("gui_stuff/icons/PO_receiving_energyUntitled.png"))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(980, 740, 151, 31))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(920, 780, 41, 31))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("gui_stuff/icons/da_charging.png"))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(980, 780, 151, 31))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(920, 820, 41, 31))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("gui_stuff/icons/da_charging2.png"))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(980, 820, 151, 31))
        self.label_24.setObjectName("label_24")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1113, 34))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.extra()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simulation"))
        self.label_time.setText(_translate("MainWindow", "Time to end:"))
        self.label_vehicles.setText(_translate("MainWindow", "Vehicles:"))
        self.label_priority.setText(_translate("MainWindow", "Priority Vehicles:"))
        self.label_stations.setText(_translate("MainWindow", "Stations:"))
        self.label_outages.setText(_translate("MainWindow", "Power Outages:"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.disp_time.setText(_translate("MainWindow", "0"))
        self.disp_vehicles.setText(_translate("MainWindow", "0"))
        self.disp_stations.setText(_translate("MainWindow", "0"))
        self.disp_priority.setText(_translate("MainWindow", "0"))
        self.disp_outages.setText(_translate("MainWindow", "0"))
        self.btn_step.setText(_translate("MainWindow", "Step"))
        self.btn_stop.setText(_translate("MainWindow", "Stop"))
        self.label_redistribution.setText(_translate("MainWindow", "Redistribution:"))
        self.disp_redistribution.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "EB"))
        self.label_4.setText(_translate("MainWindow", "Normal DA"))
        self.label_6.setText(_translate("MainWindow", "Priority DA"))
        self.label_8.setText(_translate("MainWindow", "PO w/ Energy"))
        self.label_9.setText(_translate("MainWindow", "CH w/ Energy"))
        self.label_11.setText(_translate("MainWindow", "CH wo/ Energy"))
        self.label_po_energy.setText(_translate("MainWindow", "PO Energy:"))
        self.label_car_wo_energy.setText(_translate("MainWindow", "Cars wo/ Energy"))
        self.label_car_charging.setText(_translate("MainWindow", "Cars Charging"))
        self.label_worst_time.setText(_translate("MainWindow", "Worst wait time:"))
        self.label_architecture.setText(_translate("MainWindow", "Architecture:"))
        self.disp_car_charging.setText(_translate("MainWindow", "0"))
        self.disp_po_energy.setText(_translate("MainWindow", "0"))
        self.disp_car_wo_energy.setText(_translate("MainWindow", "0"))
        self.disp_worst_time.setText(_translate("MainWindow", "0"))
        self.disp_architecture.setText(_translate("MainWindow", "-"))
        self.label_16.setText(_translate("MainWindow", "EB Redistribution"))
        self.label_18.setText(_translate("MainWindow", "EB Outage"))
        self.label_14.setText(_translate("MainWindow", "PO"))
        self.label_20.setText(_translate("MainWindow", "PO Charging"))
        self.label_22.setText(_translate("MainWindow", "Normal DA charging"))
        self.label_24.setText(_translate("MainWindow", "Priority DA charging"))

    def extra(self):
        self.disp_time.setText("0")
        self.disp_vehicles.setText("0")
        self.disp_stations.setText("0")
        self.disp_priority.setText("0")
        self.disp_outages.setText("0")
        self.btn_start.setStyleSheet("background-color: green")
        self.btn_start.clicked.connect(self.click_start)
        self.btn_step.setStyleSheet("background-color: #1aa3ff")
        self.btn_step.clicked.connect(self.click_step)
        self.btn_stop.setStyleSheet("background-color: red")
        self.btn_stop.clicked.connect(self.click_stop)

        self.map = map.map()
        self.reload_map()


    def click_start(self):
        self.default_map()
        self.disp_time.setText("0")
        print("start")
        self.sim = simulation.simulation()
        self.sim.test( self.map, self)

        

    def click_step(self):
        self.reload_map()
        self.disp_time.setText("1")
        print("step")
        
    def click_stop(self):
        self.empty_map()
        self.disp_time.setText("2")
        self.sim.stop()
        print("stop")
    
    def click_1_1(self):
        print("click_1_1")

    def click_1_N(self):
        print("click_1_N")

    def click_N_1(self):
        print("click_N_1")

    def click_N_N(self):
        print("click_N_N")


    def default_map(self):
        #self.map
        self.label_map.setPixmap(QtGui.QPixmap("images/Alameda_buildings.png"))

    def empty_map(self):
        self.label_map.setText(" ")

    def reload_map(self):
        reload_result = self.map.reload_frame()

        ax = reload_result[1]

        qimage = self.canvasToQImage(ax.figure.canvas)

        # how to get the image of a map
        #mapImg = pygame.image.fromstring(new_map[0], new_map[1], "RGB")

        self.label_map.setPixmap(QtGui.QPixmap(qimage))


    def canvasToQImage(self, canvas):
        data = canvas.buffer_rgba()
        ch = 4
        w, h = canvas.get_width_height()
        bytesPerLine = ch * w
        img = QtGui.QImage(data, w, h, bytesPerLine, QtGui.QImage.Format_ARGB32)
        return img.rgbSwapped()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
